### ISSUE TITLE
Graphviz Dot dependency

### ISSUE THREAD

**Issue by ielizaga** [stephendotcarter/greenplum-syscat-ref#2]
Requires Graphviz OS graph visualization software to execute generate_content.py. Otherwise execution will fail with:

```
Generating graphs:
  gp_configuration ... Traceback (most recent call last):
  File "generate_content.py", line 36, in <module>
    env = Environment(loader=PackageLoader('generate_content', '.'))
  File "/Users/ielizaga/Code/greenplum-syscat-ref/greenplum-syscat-ref-venv/lib/python2.7/site-packages/jinja2/loaders.py", line 224, in __init__
    provider = get_provider(package_name)
  File "/Users/ielizaga/Code/greenplum-syscat-ref/greenplum-syscat-ref-venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 396, in get_provider
    __import__(moduleOrReq)
  File "/Users/ielizaga/Code/greenplum-syscat-ref/generate_content.py", line 274, in <module>
    subprocess.call(["dot", "-Tsvg", "html/img/{0}.dot".format(relname), "-o", "html/img/{0}.svg".format(relname)])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by stephendotcarter** [comment]
Updated README with dependencies!
